# Generated by Django 6.0.2 on 2026-03-05 18:48

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=books.models.get_cloudinary_storage, upload_to='books/covers/'),
        ),
    ]
